### ISSUE TITLE
USART Connector shown on page 3 missing

### ISSUE THREAD

**Issue by robrussell** [robotics-masters/mm1-hat-schematics#1]
The USART connector doesn't appear to be present on production boards. Was this replaced with the Grove connector? I'd like to connect a peripheral to a microcontroller UART but it's not clear where to find one.

**Comment by wallarug** [comment]
Hi @robrussell ,

Correct.  The USART connector was removed and replaced with the SeeedStudio Groove Connector.

For USART you can use the GROVE connector.  It has TX and RX broken out.   There are other options available as well.  All the RCC pins are USART compatible - including 4 pin mode.  The GPS header has USART on it as well.   

The SPI pins can be used as USART if you program them that way.

The SAMD51 gives you a lot of flexibility in which pins you can use.

The latest pin out with pin numbers can be found here:

![pinout_map](https://user-images.githubusercontent.com/11770912/76483720-db323380-646b-11ea-9da3-cd7597613bdb.jpg)

This was included with all shipped packages.

**Comment by robrussell** [comment]
Thanks @wallarug ! The pinout is helpful and it will let me find an appropriate place to connect my R-XSR receiver. Will the schematics in this repo also be updated though?

**Comment by wallarug** [comment]
Hi @robrussell ,

I will try and update them tonight after work.

**Comment by wallarug** [comment]
Hey @robrussell  it has been updated.

I don't know how to update the json file.
